swipe:
  3:
    left:
      command: 'ydotool key alt+Right'
    right:
      command: 'ydotool key alt+Left'
    up:
      command: 'ydotool key ctrl+shift+t'
      threshold: 1.5
    down:
      command: 'ydotool key ctrl+w'
      threshold: 1.5
  4:
    left:
      command: 'i3-msg workspace prev'
    right:
      command: 'i3-msg workspace next'
    up:
      command: 'ydotool key super+a'
    down:
      command: '~/.config/i3/lock.sh'
pinch:
  2:
    in:
      command: 'ydotool key ctrl+plus'
      threshold: 0.1
    out:
      command: 'ydotool key ctrl+minus'
      threshold: 0.1

threshold:
  swipe: 0.7
  pinch: 0.2

interval:
  swipe: 1
  pinch: 0.2
