swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
    right:
      command: 'xdotool key alt+Left'
    up:
      command: 'xdotool key ctrl+shift+t'
      threshold: 1.5
    down:
      command: 'xdotool key ctrl+w'
      threshold: 1.5
  4:
    left:
      command: 'i3-msg workspace prev'
    right:
      command: 'i3-msg workspace next'
    up:
      command: 'xdotool key super+a'
    down:
      command: 'i3lock -t -i ~/.config/i3/lockscreen.png && sleep 1'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
      threshold: 0.1
    out:
      command: 'xdotool key ctrl+minus'
      threshold: 0.1

threshold:
  swipe: 0.7
  pinch: 0.2

interval:
  swipe: 1
  pinch: 0.2
